## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [26]:
import os
import numpy as np
import pandas as pd

In [27]:
# 設定 data_path
dir_data = 'C:/Users/rich chang/Documents/GitHub/3rd-ML100Days/data'

In [28]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: C:/Users/rich chang/Documents/GitHub/3rd-ML100Days/data\application_train.csv


### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [25]:
print("row size: ", app_train.shape[0])
print("column size: ", app_train.shape[1])

row size:  307511
column size:  122


#### 列出所有欄位

In [16]:
# app_train.columns
app_train.columns.values.tolist()


['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_A

#### 截取部分資料

In [29]:
#app_train.head(5)
app_train.head()


SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
3      100006       0         Cash loans           F            N   
4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        NaN                       NaN   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 122 columns]

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子

In [36]:
# type 'DataFrame'

df_s1 = app_train 
print(df_s1)


        SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0           100002       1         Cash loans           M            N   
1           100003       0         Cash loans           F            N   
2           100004       0    Revolving loans           M            Y   
3           100006       0         Cash loans           F            N   
4           100007       0         Cash loans           M            N   
5           100008       0         Cash loans           M            N   
6           100009       0         Cash loans           F            Y   
7           100010       0         Cash loans           M            Y   
8           100011       0         Cash loans           F            N   
9           100012       0    Revolving loans           M            N   
10          100014       0         Cash loans           F            N   
11          100015       0         Cash loans           F            N   
12          100016       0         Cas

In [35]:
idx = df_s1.index  # index
print(idx)


RangeIndex(start=0, stop=307511, step=1)


In [38]:
column_idx = df_s1.columns  # the column index
print(column_idx)


Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)


In [39]:
row_idx = df_s1.index  # the row index
print(row_idx)


RangeIndex(start=0, stop=307511, step=1)


In [40]:
print(app_train.iloc[0])
print("----------------------------------------------------------------")

SK_ID_CURR                                           100002
TARGET                                                    1
NAME_CONTRACT_TYPE                               Cash loans
CODE_GENDER                                               M
FLAG_OWN_CAR                                              N
FLAG_OWN_REALTY                                           Y
CNT_CHILDREN                                              0
AMT_INCOME_TOTAL                                     202500
AMT_CREDIT                                           406598
AMT_ANNUITY                                         24700.5
AMT_GOODS_PRICE                                      351000
NAME_TYPE_SUITE                               Unaccompanied
NAME_INCOME_TYPE                                    Working
NAME_EDUCATION_TYPE           Secondary / secondary special
NAME_FAMILY_STATUS                     Single / not married
NAME_HOUSING_TYPE                         House / apartment
REGION_POPULATION_RELATIVE              

In [41]:
print(app_train.iloc[1])
print("")


SK_ID_CURR                               100003
TARGET                                        0
NAME_CONTRACT_TYPE                   Cash loans
CODE_GENDER                                   F
FLAG_OWN_CAR                                  N
FLAG_OWN_REALTY                               N
CNT_CHILDREN                                  0
AMT_INCOME_TOTAL                         270000
AMT_CREDIT                           1.2935e+06
AMT_ANNUITY                             35698.5
AMT_GOODS_PRICE                      1.1295e+06
NAME_TYPE_SUITE                          Family
NAME_INCOME_TYPE                  State servant
NAME_EDUCATION_TYPE            Higher education
NAME_FAMILY_STATUS                      Married
NAME_HOUSING_TYPE             House / apartment
REGION_POPULATION_RELATIVE             0.003541
DAYS_BIRTH                               -16765
DAYS_EMPLOYED                             -1188
DAYS_REGISTRATION                         -1186
DAYS_ID_PUBLISH                         

In [45]:
df = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df

A         B         C         D
0  0.647324 -2.402299  0.849458 -0.520592
1 -0.850520 -0.700773 -1.484345  0.021703
2  0.224321 -1.169839 -0.236679  0.437763
3  0.829177  1.724019  1.441185 -1.812632
4  1.168277  0.845393 -1.156005  0.156309
5  0.579637 -0.049572 -0.779044  0.436492
6 -0.345806  0.901624 -2.126315 -0.581152
7  0.870941 -0.462698 -0.423275  1.082847
8  0.211856 -0.113615  0.325464  1.222848
9  0.286894 -1.327730 -0.320101  1.016658

In [46]:
n=4 
# view the front n lines
dfh = df.head(n)
print(dfh)

# view the last n lines
dft = df.tail(n) 
print(dfh)

# 各类统计信息
dfs = df.describe() 
print(dfh)

# assign rows and columns to with iloc[ , ] 
top_left_corner_df = df.iloc[:5, :5]
print(top_left_corner_df)

# transpose rows and cols
dfT = df.T 
print(dfT)


          A         B         C         D
0  0.647324 -2.402299  0.849458 -0.520592
1 -0.850520 -0.700773 -1.484345  0.021703
2  0.224321 -1.169839 -0.236679  0.437763
3  0.829177  1.724019  1.441185 -1.812632
          A         B         C         D
0  0.647324 -2.402299  0.849458 -0.520592
1 -0.850520 -0.700773 -1.484345  0.021703
2  0.224321 -1.169839 -0.236679  0.437763
3  0.829177  1.724019  1.441185 -1.812632
          A         B         C         D
0  0.647324 -2.402299  0.849458 -0.520592
1 -0.850520 -0.700773 -1.484345  0.021703
2  0.224321 -1.169839 -0.236679  0.437763
3  0.829177  1.724019  1.441185 -1.812632
          A         B         C         D
0  0.647324 -2.402299  0.849458 -0.520592
1 -0.850520 -0.700773 -1.484345  0.021703
2  0.224321 -1.169839 -0.236679  0.437763
3  0.829177  1.724019  1.441185 -1.812632
4  1.168277  0.845393 -1.156005  0.156309
          0         1         2         3         4         5         6  \
A  0.647324 -0.850520  0.224321  0.829177  

In [47]:
# Some attributes of df

# list row and col indexes
l = df.axes
print(l)

# from above??????
(r, c) = df.axes 
print((r,c))

# Series column data types
s = df.dtypes
print(s)

# True for empty DataFrame
b = df.empty
print(b)

# number of axes (2)
i = df.ndim 
print(i)

 # (row-count, column-count)
t = df.shape
print(t)

# from above
(r, c) = df.shape 
print((r,c))

# row-count * column-count
i = df.size 
print(i)

# get a numpy array for df
a = df.values 
print(a)

[RangeIndex(start=0, stop=10, step=1), Index(['A', 'B', 'C', 'D'], dtype='object')]
(RangeIndex(start=0, stop=10, step=1), Index(['A', 'B', 'C', 'D'], dtype='object'))
A    float64
B    float64
C    float64
D    float64
dtype: object
False
2
(10, 4)
(10, 4)
40
[[ 0.6473237  -2.40229933  0.84945767 -0.52059247]
 [-0.85052022 -0.70077251 -1.48434484  0.02170327]
 [ 0.22432125 -1.1698394  -0.23667872  0.43776329]
 [ 0.82917656  1.72401904  1.44118462 -1.81263174]
 [ 1.16827679  0.84539336 -1.15600475  0.15630856]
 [ 0.57963682 -0.04957176 -0.7790439   0.43649226]
 [-0.34580629  0.901624   -2.12631515 -0.58115169]
 [ 0.87094115 -0.46269842 -0.4232751   1.08284671]
 [ 0.21185634 -0.11361487  0.32546431  1.22284774]
 [ 0.28689368 -1.32772953 -0.32010078  1.01665845]]


In [50]:
# label, list

df = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
idx = df.columns  # get col index
label = df.columns[0:3]  # 1st col label
lst = df.columns.tolist()  # get as a list
print(idx)
print(label)
print(lst)


Index(['A', 'B', 'C', 'D'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')
['A', 'B', 'C', 'D']


In [51]:
print(df.columns.tolist())
print(df.index.tolist())
print(df.loc['two':'three'])
df.iloc[:, 1:2]

['A', 'B', 'C', 'D']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Empty DataFrame
Columns: [A, B, C, D]
Index: []


B
0  0.014306
1  0.386902
2 -1.011440
3  2.906724
4 -0.828242
5 -1.440986
6  0.113547
7 -0.627725
8 -0.138624
9  2.455865